import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import "./globals.css";
// import Navbar from "@/components/common/Navbar";
import { AdminsThemeProvider } from "@/components/theme/AdminsThemeProvider";
import { DeveloperNavbar } from "@/components/Navbar/DeveloperNavbar";
import { DeveloperSidebar } from "@/components/Sidebar/DeveloperSidebar";
import { StoreProvider } from "@/lib/store/Provider";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <AdminsThemeProvider>
            {/* <Navbar /> */}
            {/* <React.StrictMode>
              {children}
            </React.StrictMode> */}
            <>
              {children}
            </>
            <ToastContainer
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop
              closeOnClick
              // stacked
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
            {/* <Providers /> */}
          </AdminsThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
